# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'vkontakte' do
  use_frameworks!
  pod 'INSPhotoGallery'
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'SwiftyJSON'
end
