# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'vkontakte' do
  use_frameworks!
  pod 'INSPhotoGallery'
  pod 'Alamofire'
  pod 'RealmSwift'
  pod 'Kingfisher'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
end
