# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'vkontakte' do
  use_frameworks!
  pod 'INSPhotoGallery'
  pod 'Alamofire'
  pod 'RealmSwift'
  pod 'Kingfisher'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.14.0'
end
